site_name: Easy Install WSL Linux

repo_name: Easy-Install-WSL-Linux
repo_url: https://github.com/KsQRooW/Easy-Install-WSL-Linux
edit_uri: ''

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: custom-color
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Tutorial: index.md
  - Support: support.md

extra_css:
  - 'custom.css'
